import { makeStyles } from "@material-ui/core";

export default makeStyles((theme) => ({
  indexMain: {
    display: "flex",
    [theme.breakpoints.down(1250)]: {
      display: "block",
    },
  },
  paper: {
    maxWidth: '450px',
    background: "#333333",
    backgroundColor: "#333333",
    marginTop: theme.spacing(2),
    display: "block",
    textAlign: "center",
    paddingLeft: theme.spacing(8),
    paddingRight: theme.spacing(8),
    color: '#ffffff',
    margin: theme.spacing(2),
    [theme.breakpoints.down(450)]: {
      paddingLeft: theme.spacing(3),
    paddingRight: theme.spacing(3),
    },
  },
  finnishButton: {
    background: "#39A628",
    color: "white",
    marginTop: theme.spacing(2),
    marginBottom: theme.spacing(4),
    borderRadius: "5em",
    marginRight: "10px",
    marginLeft: "10px",
    paddingLeft: theme.spacing(10),
    paddingRight: theme.spacing(10),
  },
  SetUpCompliance: {
    maxWidth: "470px",
    minWidth: "470px",
    background: "#333333",
    backgroundColor: "#333333",
    color: "white",
    cursor: "pointer",
    marginRight: theme.spacing(4),
    marginTop: theme.spacing(2),
    marginBottom: theme.spacing(4),
    paddingTop: "80px",
    paddingBottom: "80px",
    paddingLeft: "100px",
    paddingRight: "30px",
    display: "flex",
    textAlign: "center",
    minHeight: 175,
    [theme.breakpoints.down(1000)]: {
      minWidth: "10px",
      minHeight: "auto",
    },
    [theme.breakpoints.down(730)]: {
      paddingLeft: "10px",
      marginRight: "none",
      paddingRight: "10px",
      margin: theme.spacing(2),
    },
  },
  Icon: {
    fontSize: "150px",
    paddingRight: "80px",
    [theme.breakpoints.down(800)]: {
      paddingRight: "10px",
      fontSize: "100px",
    },
  },
  Label: {
    textAlign: "left",
  },
  EditCompliance: {
    maxWidth: "470px",
    minWidth: "470px",
    background: "#333333",
    backgroundColor: "#333333",
    color: "white",
    cursor: "pointer",
    marginRight: theme.spacing(4),
    marginTop: theme.spacing(2),
    marginBottom: theme.spacing(4),
    paddingTop: "80px",
    paddingBottom: "80px",
    paddingLeft: "100px",
    paddingRight: "30px",
    display: "flex",
    textAlign: "center",
    minHeight: 175,
    [theme.breakpoints.down(1000)]: {
      minWidth: "10px",
      minHeight: "auto",
    },
    [theme.breakpoints.down(730)]: {
      paddingLeft: "10px",
      marginRight: "none",
      paddingRight: "10px",
      margin: theme.spacing(2),
    },
  },
  layout: {
    maxWidth: '450px',
    background: "#333333",
    backgroundColor: "#333333",
    marginTop: theme.spacing(2),
    marginBottom: theme.spacing(2),
    display: "block",
    textAlign: "center",
    paddingLeft: theme.spacing(8),
    paddingRight: theme.spacing(8),
    [theme.breakpoints.down(650)]: {
      paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2),
    },
  },
  Heading: {
    paddingTop: theme.spacing(4),
    color: "rgba(255,255,255,1)",
    textAlign: "left",
    fontWeight: 600,
    fontSize: "24px",
  },
  subHeading: {
    paddingTop: theme.spacing(1),
    color: "rgba(255,255,255,1)",
    textAlign: "left",
    fontWeight: 600,
    fontSize: "18px",
  },
  altHeading: {
    color: "rgba(211,211,211,1)",
    textAlign: "left",
    fontWeight: 600,
    fontSize: "18px",
  },
  checkBox: {
    color: '#ffffff',
    float: "left",
  },
  checkboxLabels: {
    color: "white",
    paddingLeft: "15px",
    fontSize: "18px",
    fontWeight: 600,
    [theme.breakpoints.down(520)]: {
      fontSize: "12px",
      paddingLeft: "0px",
    },
  },
  ComplianceNext: {
    background: "#9A2849",
    backgroundColor: "#9A2849",
    color: "white",
    borderRadius: "5em",
    fontWeight: "bold",
    width: "100%",
    height: "39px",
    marginTop: theme.spacing(3),
    marginBottom: theme.spacing(4),
  },
  textField: {
    backgroundColor: "#fff",
    text: "white",
    width: "94%",
    height: "40px",
    border: "none",
    fontSize: "18px",
    paddingLeft: "20px",
    borderRadius: "5px",
    outline: "none",
    marginBottom: theme.spacing(4),
  },
  frameworkBack: {
    background: "#9A2849",
    backgroundColor: "#9A2849",
    color: "white",
    borderRadius: "5em",
    fontWeight: "bold",
    width: "100%",
    height: "39px",
    marginRight: "10px",
    marginBottom: theme.spacing(2),
  },
  frameworkSubmit: {
    background: "#39A628",
    backgroundColor: "#39A628",
    color: "white",
    borderRadius: "5em",
    fontWeight: "bold",
    width: "100%",
    height: "39px",
    marginBottom: theme.spacing(2),
  },
  altHeadingFinal: {
    color: "rgba(211,211,211,1)",
    textAlign: "left",
    fontWeight: 600,
    fontSize: "18px",
    marginTop: theme.spacing(4),
  },
  backToCompliance: {
    background: "#9A2849",
    backgroundColor: "#9A2849",
    color: "white",
    borderRadius: "5em",
    fontWeight: "bold",
    width: "100%",
    height: "39px",
    marginTop: theme.spacing(2),
    marginBottom: theme.spacing(4),
  },
  mainGrid: {
    width: "1200px",
    color: "white",
    [theme.breakpoints.down(1200)]: {
      width: "auto",
    },
  },
  editGrid: {
    background: "#333333",
    backgroundColor: "#333333",
    color: "white",
    paddingLeft: "90px",
    paddingTop: "20px",
    paddingBottom: "40px",
    marginBottom: "20px",
    [theme.breakpoints.down(650)]: {
      paddingLeft: "10px",
      paddingTop: "10px",
      paddingBottom: "20px",
    },
  },
  firstGrid:{
    marginRight: "200px",
    [theme.breakpoints.down(1200)]: {
      marginRight: "50px",
    },
  },
  secondGrid:{
    marginRight: "40px",
    [theme.breakpoints.down(990)]: {
      marginTop: "30px"
    },
  },
  configBasedGrid: {
    paddingLeft: "250px",
    [theme.breakpoints.down(1200)]: {
      paddingLeft: "100px",
      paddingRight: "90px"
    },
    [theme.breakpoints.down(1090)]: {
      paddingLeft: "10px",
      paddingRight: "90px"
    },
  },
  edtSubmitBtn: {
    background: "#9A2849",
    backgroundColor: "#9A2849",
    color: "white",
    borderRadius: "5em",
    width: "250px",
    height: "39px",
    marginBottom: theme.spacing(2),
    marginLeft: theme.spacing(2),
    [theme.breakpoints.down(730)]: {
      marginLeft: "0px",
    },
  },
  edtBackBtn: {
    background: "#333333",
    backgroundColor: "#333333",
    color: "white",
    borderRadius: "5em",
    width: "250px",
    height: "39px",
    marginBottom: theme.spacing(2),
  },
}));